apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: cluster.k8s
      http:
        paths:
          - path: /esw
            pathType: Prefix
            backend:
              service:
                name: email-service-worker-load-balancer
                port:
                  number: 90
          - path: /nass
            pathType: Prefix
            backend:
              service:
                name: new-account-signup-service-load-balancer
                port:
                  number: 91
          - path: /prs
            pathType: Prefix
            backend:
              service:
                name: password-reset-service-load-balancer
                port:
                  number: 92